### ISSUE TITLE
Consider using license expressions rather than a list of licenses

### ISSUE THREAD

**Issue by pombredanne** [CycloneDX/specification#1]
These are specified in SPDX and provide a clean short hand for eventually complex licensing. See for instance its emerging use in the latest Linux kernel. NB: I helped there and I am an SPDX co-founder.

**Comment by stevespringett** [comment]
Note: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60

**Comment by stevespringett** [comment]
Included in CycloneDX 1.1
