### ISSUE TITLE
Cyclone dx bom as a yaml file

### ISSUE THREAD

**Issue by sameer1046** [CycloneDX/specification#104]
Can we have support for yaml file as cyclone dx bom specification in future?

**Comment by stevespringett** [comment]
We currently do not have plans on supporting YAML.

What use cases could YAML uniquely provide that is not being achieved with JSON, XML, or Protobuf today?

**Comment by jkowalleck** [comment]
if you need to support YAML, you could pick the existing JSON schema and define it to be applied on YAML data structures as well. this is possible as JSON is a subset of YAML (but more braces, less spaces).
no further work needed, afaik.

one benefit of YAML: allows comments

**Comment by sameer1046** [comment]
Correct ! Its possible to convert json to yaml easily. Just wanted to know what's the plan. Thanks
