### ISSUE TITLE
Remove CPE deprecation

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#105]
The NVD deprecated CPE several years ago with David Waltermire stating there would be no further improvements to the spec. The NVD had plans on migrating to SWID tags which is documented in [NISTIR 8060](https://csrc.nist.gov/publications/detail/nistir/8060/final). Based on conversations the CycloneDX Core Working Group has had with NIST, it is our understanding that many/all CVE's have auto-generated SWID tags associated with them in a lab environment. However, the NVD has failed thus far to provide guidance or timelines for CPE -> SWID migration.

Currently, CPE is deprecated in CycloneDX as a preemptive measure that would align with the NVD. Due to the current state of the NVD and a lack of external communication regarding the migration for the past few years, I recommend removing the deprecated status from CPE.

This is a documentation change only.

**Comment by coderpatros** [comment]
+1

**Comment by adulau** [comment]
Thank you!
