### ISSUE TITLE
Add support for Low-Code Application Platforms (LCAP)

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#113]
Many enterprise applications are developed and deployed to Low-Code Application Platforms (LCAP). These applications may consist of configuration, a minimum amount of code, workflow, and integrations.

Low-code components should be considered for a future version of the CycloneDX spec. Example LCAP platforms include:

* Appian
* Mendix
* Salesforce
* ServiceNow

**Comment by stevespringett** [comment]
Semi-related is a new OWASP Top 10 project for low-code 
https://owasp.org/www-project-top-10-low-code-no-code-security-risks/

**Comment by stevespringett** [comment]
Possibly reach out to https://www.prophecy.io/ as they have a low code platform and a COSS model.

**Comment by mbrg** [comment]
> Semi-related is a new OWASP Top 10 project for low-code https://owasp.org/www-project-top-10-low-code-no-code-security-risks/

Hi, I lead the project above. We'd be happy to collaborate!

**Comment by stevespringett** [comment]
Support for low-code apps have been implemented indirectly through component type expansion and machine learning enhancements. Together, these two enhancements had everything necessary for low-code apps. This include:

- New `platform` and `data` component type
- Data components that can contain source code, configuration, and templates

This should make it possible to support any low-code app and any citizen developed app.
