### ISSUE TITLE
make `ref`/`bom-ref` own data type in schema

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/specification#114]
## motivation: 

in current(spec<=1.3, 1.4-dev) schema files the definition of `ref` and `bom-ref` are defined as an arbitrary string.
Basically both are simple strings, but a `ref` should be a value that was used as a `bom-ref` in another place, so both strings are from the same "string-class" and unlike other arbitrary strings. 
The fact that both strings are interlinked is made clear in comments, but not in the DataType itself.

To make the relation between these values more clear, i would love to introduce an schema-based string type that extends "string" and is used for `bom-ref`-based object-interlinks.

## scope

schema 1.1 XML
schema 1.2 XML & JSON
schema 1.3 XML & JSON
schema 1.4-dev XML & JSON

## acc / crit: 
* changes to the schema may add additional documentations
* changes to the schema must not change any structure or data-types.
* changes to the schema must not add any new features on data-level

## implementation details 

* call new DataType "refType"
* new DataType must inherit "string"-type
* new DataType should be made publicly available, so other schemas or extensions can use it to point out that elements are interlinked.

**Comment by stevespringett** [comment]
Is this still an issue? Changes to prior schemas will not be made, but if this issue is still present in v1.5-dev branch, we have time to correct it (assuming doing so is backward compatable).

**Comment by jkowalleck** [comment]
@stevespringett re: https://github.com/CycloneDX/specification/issues/114#issuecomment-1399621548

:heavy_check_mark: The feature was already introduced in v1.4 via #116.

Additionally, #115 would back-port the features into older specs without breaking changes. Take it or leave it, you decide.
Feel free to close this PR and mark #115 as "closed as not planned"

**Comment by jkowalleck** [comment]
will close it.
for me (the author of this ticket) the currently implemented fixes are good enough
