### ISSUE TITLE
SBOM `mimeType` XML schema type incorrectly uses anchors in regex pattern

### ISSUE THREAD

**Issue by dmeibusch** [CycloneDX/specification#122]
Appears the only XS regex `pattern` in the spec that fell into this gotcha (https://www.regular-expressions.info/xml.html  by including anchors (`^` and `$`) in the pattern.

```XML
    <xs:simpleType name="mimeType">
        <xs:restriction base="xs:token">
            <xs:pattern value="^[-+a-z0-9.]+/[-+a-z0-9.]+$"/>
        </xs:restriction>
    </xs:simpleType>
```
It doesn't seem to be consistently implemented in schema validators. The current `cyclonedx-core-java` library will reject (fail to validate) any document that has a mime type for a component.

**Comment by stevespringett** [comment]
Interesting. Thanks for reporting. Looks like this was introduced in CycloneDX v1.2, so it's been in there a while. Of the hundreds of unit tests we have for the schema, this one is missing a test.

The same pattern is also used in the JSON schema, however, JSON schema supports the `^` and `$` anchors.

I have not referred to the XSD spec, so wondering if you have... If the anchors are not supported by XSD, is the correct behavior of validators to drop/ignore the characters or to fail? We will obviously need to fix this in CycloneDX, however, I'm also curious if the validators themselves need fixes.

**Comment by dmeibusch** [comment]
I haven't tested example what the `javax.xml` validator is doing in `cyclonedx-core-java`. I suspect it follows the XSD spec exactly where `^` and `$` are not to be respected as regex metacharacters. Hence a match would have to contain these characters. I've seen comments in stackoverflow that validators on other platforms pass the pattern directly through to a regex library, not respecting the XSD restrictions on patterns.

**Comment by stevespringett** [comment]
The regex has been corrected and will be incorporated into newer versions of official CycloneDX implementations, including Core Java.

**Comment by stevespringett** [comment]
CycloneDX Core Java v7.1.2 has been released and includes maintenance schema updates.
