### ISSUE TITLE
Schema Maintenance Releases

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#124]
XML Schema 1.2 - 1.4 has an invalid regex for mime-type. (#122) 

JSON Schema 1.2-1.3 has duplicate $id's in several places (#123, #84, #125)

---

### Objective

Create backward-compatible maintenance releases that have minimal impact

---

### XML Versioning

XSD namespaces will remain the same:
```
http://cyclonedx.org/schema/bom/1.2
http://cyclonedx.org/schema/bom/1.3
http://cyclonedx.org/schema/bom/1.4
```
however, the `xs:schema version` will bump to `1.2.1`, `1.3.1`, and `1.4.1`.

---
### JSON Versioning

The `$id` of the schema will bump to:
```
http://cyclonedx.org/schema/bom-1.2b.schema.json
http://cyclonedx.org/schema/bom-1.3a.schema.json
```

### Deployment

The JSON and XML schemas should replace the schemas available in official CycloneDX implementations including .NET, Core Java, and others. Additionally, the schemas should be deployed to cyclonedx.org replacing the originals. Original schemas will continue to be available on GitHub via the git tag of the release. These releases are immutable, however, it serves the global community to have defect free schemas (where possible) for older versions of the spec.

**Comment by jkowalleck** [comment]
any updates, @stevespringett ?

**Comment by stevespringett** [comment]
@jkowalleck working on it now in preparation for tomorrows CycloneDX Core Working Group meeting.

**Comment by stevespringett** [comment]
Schema maintenance releases have been published.
