### ISSUE TITLE
Manufacturer spelling error?

### ISSUE THREAD

**Issue by elear** [CycloneDX/specification#126]
Version 1.4:

Around line 141 the schema uses "manufacture" and note "manufacturer".  Was this intentional?  The description would lead one to believe that it is an error.

**Comment by stevespringett** [comment]
Indeed, it is misspelled and is an unfortunate mistake along the same lines as http "referer".

Duplicate of #57

**Comment by elear** [comment]
Ok then.  Should be closed as a dup?
