### ISSUE TITLE
Security Contact Signposting 

### ISSUE THREAD

**Issue by yosignals** [CycloneDX/specification#128]
It would be nice if there was room for security signposting within the application, doing so would yield a clear path to contacting a security audience should the need to reach them present. 

I think the scope of this could be light, it's a security contact that would inherit any demonstrable concern - whatever medium they want to use as a means to contact is on those owners 

ultimately knowing something isn't safe is useful, but knowing exactly who to speak too should allow for a faster reaction time 

we need more ways to reach the right people, and with the web and software being so diverse, I suppose the options have to be too, any means is good, but this is a nice opportunity to get in there early 

Thanks!

**Comment by coderpatros** [comment]
Suggested approach, create a security contact external reference type. Can use `mailto` and `tel` URL schemes. As well as supporting comments or URLs that point to contact pages, etc. This would cover security contacts for the assembled software, individual software components/assemblies, and services.

**Comment by yosignals** [comment]
this isn't about contracts or about any legal obligations (or otherwise) I don't understand why you've framed it this way

there is nothing overwhelming in citing a means to be reached for the safety of data and infrastructure that houses it

The only convoluted means of security contact is not doing this.

Happy to disagree with you 😊

**Comment by stevespringett** [comment]
@yosignals I think using the approach that @coderpatros mentioned above, we can accommodate DNS Security Text as well. For example, the following conforms to RFC-4501 and allows us to specify DNS TXT records for a domain.
```
dns:www.example.org.?CLASS=IN&TYPE=TXT
```

So we could theoretically have zero or more of the following examples as external references:

```
mailto:security@example.org
tel:+1-800-555-1212
dns:www.example.org.?CLASS=IN&TYPE=TXT
```

Would this work @yosignals

**Comment by yosignals** [comment]
Hey Steve ! No grumbles from me:) 🤙Sent from my iPhoneOn 23 Jan 2023, at 03:37, Steve Springett ***@***.***> wrote:﻿
@yosignals I think using the approach that @coderpatros mentioned above, we can accommodate DNS Security Text as well. For example, the following conforms to RFC-4501 and allows us to specify DNS TXT records for a domain.
dns:www.example.org.?CLASS=IN&TYPE=TXT

So we could theoretically have zero or more of the following examples as external references:
***@***.***
tel:+1-800-555-1212
dns:www.example.org.?CLASS=IN&TYPE=TXT

Would this work @yosignals

**Comment by stevespringett** [comment]
Scheduled for inclusion in v1.5
