### ISSUE TITLE
CLI convert doesn't support dependencies

### ISSUE THREAD

**Issue by tidepodz** [CycloneDX/specification#134]
the example.csv file does not have an example of a dependencies column. I've included a dependencies column on some SBOM csv files I've created and so far I have not been able to get them to populate in the json file produced from "./cyclonedx-linux-x64 convert  ...."

**Comment by jkowalleck** [comment]
Hello @tidepodz,

Is there an issue to report, or do you have a question or need help? 
Is the topic related to the specifications, or related to [the CLI tool](https://github.com/CycloneDX/cyclonedx-cli)?

**Comment by tidepodz** [comment]
@jkowalleck 
Thanks for responding. I'm now realizing I may have put this in the wrong spot, it is related to the CLI tool. 

Its a bit of a two part question issue. Is the CLI supposed to support the 'dependencies' field of CycloneDX? I would have assumed it to support the full standard? If it does can an example be added to https://github.com/CycloneDX/cyclonedx-cli/blob/main/example.csv
