### ISSUE TITLE
Vulnerability analysis using Dependency Tracker 

### ISSUE THREAD

**Issue by skunal** [CycloneDX/specification#149]
Since, dependency tracker uses the tags: cpe, swid or purl to find the vulnerabilities from NVD database. 

CycloneDX should make existence of any of such tags mandatory for cycloneDX xml files. 

If these tags are not mandatory then fetching data from NVD becomes a challenge.

**Comment by stevespringett** [comment]
Vulnerability management is the primary use case and the reason why the world is talking about SBOM. However, license and other non-security use cases are important and CycloneDX needs to support those.

**Comment by coderpatros** [comment]
CycloneDX is capable of more than just SBOM use cases. Some components simply won't have a CPE, SWID or PURL. Certainly, if these identifiers are known they should be included. But I don't think we can enforce it in the spec itself.

**Comment by stevespringett** [comment]
I think the upcoming [BOM Maturity Model](https://scvs.owasp.org/bom-maturity-model/) from OWASP SCVS will be helpful to you. In that, you'll be able to make whatever fields you want mandatory by creating profiles. Several developers are already waiting for SCVS to release the maturity model so they can develop SBOM Profiles and policy enforcement tools specific to this purpose.

Closing issue
