### ISSUE TITLE
Is 'application' default software component classification? Possible doc update

### ISSUE THREAD

**Issue by mlinksva** [CycloneDX/specification#16]
https://github.com/CycloneDX/specification/blob/aa6dea146b6a8af531e5ba1e9cf96ea983fa9205/schema/bom-1.1.xsd#L188-L194

https://github.com/CycloneDX/specification/blob/aa6dea146b6a8af531e5ba1e9cf96ea983fa9205/schema/bom-1.1.xsd#L307-L316

I wonder if the documentation string should instead be something like

> Specifies the type of component. If a software component cannot be classified as an application, file, framework, or operating system, the component should be classified as an application.

or

> Specifies the type of component. For software components, classify as application if no more specific appropriate classification is available or cannot be determined for the component.

**Comment by stevespringett** [comment]
Thanks for catching the doc issue. I used the clarifying text you provided as it captures the spirit of what the intended meaning was.
