### ISSUE TITLE
Add parity between protobuf specification and json/xml specification

### ISSUE THREAD

**Issue by seb06cai** [CycloneDX/specification#161]
I am writing some functionality within our system which uses protobuf to send data, and wanted to use the protobuf schemas defined here, but the schema is quite different than the json schema.

This means that when I read a CycloneDX bom file and try to serialize it to the protobuf schema, it is completely incompatible. It works when serializing to the Bom struct defined in https://github.com/CycloneDX/cyclonedx-go/blob/v0.7.0/example_test.go, but there is not protobuf equivalent for that Bom struct that I can use to define and transport the data within our system.

Is there any recommendation from the team at CycloneDX on how to deal with this currently, and if not, are there plans to improve the protobuf specification to match the actual Bom files?

**Comment by stevespringett** [comment]
Per [this thread in Slack](https://cyclonedx.slack.com/archives/CVA0G10FN/p1664913266712459), this appears to be an issue with the golang implementation, not the spec.

Closing

If you do find defects in the spec, please let us know.
