### ISSUE TITLE
Request for Additional License Fields

### ISSUE THREAD

**Issue by jheck88** [CycloneDX/specification#162]
We're finding that we could use additional fields for the License Object in the schema to better handle non opensource licenses.

Specifically having to overload the Name object doesn't seem to be the _best_ way to go about things.  

Looking to have the following optional values added:

- Expiration
- Origination
- Purchaser
- Internal ID

**Comment by stevespringett** [comment]
Can you define origination and purchaser?

**Comment by jheck88** [comment]
> Can you define origination and purchaser?

Purchaser would be in the format of `Name <email>` or regex: `(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))` 

[Example](https://regex101.com/r/pVV5TI/1)

Origination would be group or organization which the license is controlled/tracked from.  Plain text word.

**Comment by stevespringett** [comment]
The CycloneDX specification defines organizationalEntity and organizationalContact

Examples of this would be:
https://cyclonedx.org/docs/1.4/json/#components_items_supplier
and
https://cyclonedx.org/docs/1.4/json/#components_items_supplier_contact

Are there cases where Origination could be either an entity or a contact? And is there cases where a purchaser could be an entity or contact?

**Comment by jheck88** [comment]
@stevespringett Yes, those would work for both those fields.  Perhaps defined as org entity OR org contact would work for both those fields.

**Comment by stevespringett** [comment]
For expiration... My concern here is that if expiration was part of the BOM, and the license was renewed after the BOM was generated, the date in the BOM would no longer be accurate. Thoughts?

**Comment by stevespringett** [comment]
I'm wondering if license model may be more useful. For example, an enum of `perpetual`, `subscription`, etc with the option to specify terms (monthly, yearly, etc). Would this be useful? If so, can you help break down what the possible values would be?

**Comment by jheck88** [comment]
> For expiration... My concern here is that if expiration was part of the BOM, and the license was renewed after the BOM was generated, the date in the BOM would no longer be accurate. Thoughts?

Good point.  I'm thinking you could have and something like:

LicenceMetadata 
- RenewalType: perpetual|subscription
  - perpetual (no object)
  - subscription
    - annual
    - monthly
    - other (Some kind of pattern here for something like a 5 yr renewal cycle)
- LastRenewed (This would be the last renewed date at the time of bom creation)

Alternatively, that license that I've attached may not be the same if it's renewed.  So that license itself could be permanently expired.

**Comment by stevespringett** [comment]
@jheck88 thinking out loud... What are your thoughts on this?

```json
"licenses": [
  {
    "license": {
      "name": "Acme Commercial License",
      "altIds": [
      ],
      "origination": {

      },
      "purchaser": {

      },
      "licenseType": "perpetual | concurrent | floating | subscription | other",
      "subscription": "annual | monthly | other (free form text)",
      "lastRenewal": "2022-04-13T20:20:39+00:00"
    }
  }
]
```
origination and purchaser could either be an organizationalEntity or organizationalContact. altIds is simply an array of identifiers an org may have.

**Comment by jheck88** [comment]
Some comments: 

```
"licenses": [
  {
    "license": {
      "name": "Acme Commercial License",
      "altIds": [
      ],
      "purchaseOrder": "purchaseOrderId",  //  Comment 1
      "origination": {

      },
      "purchaser": {

      },
      "licenseType": "perpetual | concurrent | floating | subscription | other",
      "subscription": "annual | monthly | other (free form text)",
      "lastRenewal": "2022-04-13T20:20:39+00:00",
      "expiration": "2023-04-13T20:20:39+00:00" // Comment 2
    }
  }
]
```
1. Would be an opaque string matching an ID in a purchasing database
2. It would be nice to have expiration as a field containing an ISO standard date, so there isn't any ambiguity in calculating that.  For example, would a last renewal of April 13 plus a monthly subscription expire on May 13, May 14, or April 30?

**Comment by stevespringett** [comment]
@jheck88 for clarity, is your definition of `origination` the `licenser` (the organization or person who can issue a license or give authoritative permission)? Or is your definition something else?

**Comment by stevespringett** [comment]
Also I think if we standardize on `licenser` and `licensee` that will clarify things a bit. But the `purchaser` could infact be different then the licenser, so I think we should have both. Thoughts?

**Comment by jkowalleck** [comment]
> But the `purchaser` could infact be different than the licensee, so I think we should have both. Thoughts?

I would also see the need for the `licensee` and an additional `purchaser`.
In my org it was common practice that these two differed.

**Comment by jheck88** [comment]
> @jheck88 for clarity, is your definition of origination the licenser (the organization or person who can issue a license or give authoritative permission)? Or is your definition something else?

@stevespringett Yep, Origination == The Licenser

> But the purchaser could infact be different than the licensee, so I think we should have both. Thoughts?
> I would also see the need for the licensee and an additional purchaser.
> In my org it was common practice that these two differed.

I would agree that licensee and purchaser have a good probability of being different individuals.

**Comment by stevespringett** [comment]
Based on my understanding of the requirements, this is what I'm proposing:

```json
"license": {
    "name": "Acme Commercial License",
    "licenseProperties": {
        "altIds": [
        ],
        "licensor": {
        },
        "licensee": {
        },
        "purchaser": {
        },
        "purchaseOrder": "purchaseOrderId",
        "licenseType": "appliance | client-access | concurrent-user | core-points | custom-metric | device | perpetual | processor-points | subscription | free | user | named-user | node-locked | oem | evaluation | volume | other",
        "subscription": "annual, usage or other free form text (not an enum)",
        "lastRenewal": "2022-04-13T20:20:39+00:00",
        "expiration": "2023-04-13T20:20:39+00:00"
    }
}
```

I'm going to proceed with spec development, so please let me know if there are any changes that need to be made.

**Comment by jkowalleck** [comment]
@stevespringett 

> I do have a question regarding the name of licenseProperties. Personally, I don't like what this is called.

Me neither. 
As you are having all the properties/objects under an object that is already named "license", there is no reason for a prefix as the structures are nested.
Simply calling it `properties` is not cool, since `properties` is probably reserved to the "free" properties and must not be confused here.

I propose to go with `licensing` instead of `licenseProperties`, as the current set of properties reflects on that topic.

**Comment by jheck88** [comment]
@jkowalleck @stevespringett I agree with either `licensing` or `licensingMetadata`.  Properties are throughout the entire spec and have a unique, free-form meaning.

**Comment by stevespringett** [comment]
Great. Sounds like we have early consensus on `licensing`, so I'll move forward with that.

**Comment by DarthHater** [comment]
Do we really intend to have OrganizationalEntity AND OrganizationalContact as choices for these new fields? I'm asking because it complicates the implementation quite a bit at least for `core-java`, where we basically have to go "Well yeah, it could be one of two classes". We can do it obviously, but just asking the question to make absolutely certain we want to do that. The reason I ask is because `OrganizationalEntity` has `OrganizationalContact` on it, so you can set the appropriate information with it, I believe. cc @mr-zepol

**Comment by stevespringett** [comment]
Yes, I think entity or contact is what we want, similar to how we do it for license vs expression. 

A common scenario will be:
- Company wants to purchase license to use software from individual developer via GitHub sponsors, etc
- Individual developer grants extended license to company

**Comment by mrutkows** [comment]
The question is, based upon the scenario above, the new metadata assumes a corporate-wide license is granted which (as I can tell you in IBM) is not always the case as often the grant is limited to an org. or limited to a number... is there an ability to describe the "grant type" (or a reference to one?)

**Comment by stevespringett** [comment]
OrganizationalEntity already allows an array of OrganizationalContact, so that case is good. There's nothing in the spec that states what the license is terms are or what the grant type is.

I was expecting this to go into the existing license attachment as I think it is going to be extremely difficult to identify all the possible grant types. But we could always add a `grantType` string field to make it more obvious.

**Comment by DarthHater** [comment]
Yeah as @stevespringett said, `OrganizationalEntity` already has a `OrganizationalContact`. My quandary was a bit more goofy, in that to accept either/or as a field in code can be fun at times, hence the question on if we really want to do that.

**Comment by stevespringett** [comment]
Scheduled for inclusion in v1.5
