### ISSUE TITLE
bomFormat

### ISSUE THREAD

**Issue by damianoneill** [CycloneDX/specification#164]
Hi, looking at https://github.com/CycloneDX/specification/blob/1.4/schema/bom-1.4.proto, I don't see bomFormat.

https://cyclonedx.org/docs/1.4/json/#bomFormat - described here as "Required."

Should an enum be defined in the proto message Bom for this?

When converting a sample payload into a proto type the conversion complains about the bomFormat in the JSON message.

```
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  "version": 1,
  "components": [
    {
      "type": "library",
      "name": "acme-library",
      "version": "1.0.0"
    }
  ]
}
```

**Comment by stevespringett** [comment]
bomFormat is specific to the JSON serialization. It does not exist in XML as XML supports namespaces which tells the consumer of the document what it is.

IMO, I would simply drop bomFormat when converting from JSON to protobuf. Again, you shouldn't have this issue when converting from XML to protobuf.

@coderpatros @DarthHater thoughts?

**Comment by coderpatros** [comment]
Yeah, this is unique to the JSON format. I'm not sure there would be benefit in adding it to the protobuf format.
