### ISSUE TITLE
 generate sbom for c++ project that use custom make file

### ISSUE THREAD

**Issue by mehrdad2000** [CycloneDX/specification#165]
Hi
have an c++ project that use custom make file to build.
How can I create sbom for this project?

FYI: I don't want to use Cmake.

Any Idea?
Thanks

**Comment by stevespringett** [comment]
Have you tried asking in our Slack? 

Slack: https://cyclonedx.org/slack
Invite: https://cyclonedx.org/slack/invite

This repo is for the specification itself. Closing.
