### ISSUE TITLE
Framework vs Library

### ISSUE THREAD

**Issue by nilp0inter** [CycloneDX/specification#17]
Hi,

What is the difference between "framework" and "library"? I could not find the exact definition in the documentation.

Thank you.

**Comment by stevespringett** [comment]
In software engineering, frameworks or something software is built on
whereas library’s or something you build with.  The difference is subtle
however frameworks tend to have tighter coupling which leads to higher
operational risk.

— Steve

From: Roberto Abdelkader Martínez Pérez <notifications@github.com>
<notifications@github.com>
Reply: CycloneDX/specification
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 4, 2019 at 4:18:14 AM
To: CycloneDX/specification <specification@noreply.github.com>
<specification@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [CycloneDX/specification] Framework vs Library (#17)

Hi,

**Comment by mlinksva** [comment]
In Soviet Russia, the library calls you and it's called a framework.

Joking aside, it's not always easy to tell, and some frameworks can be used as libraries. It _might_ be worth including brief definitions, perhaps just links to external definitions or even just the relevant enwp articles, which are not bad:

- https://en.wikipedia.org/wiki/Software_framework
- https://en.wikipedia.org/wiki/Library_(computing)

I actually opened #16 upon looking up whether 'application' is an acceptable fallback given that classifying software by type is not necessarily obvious. If done without human curation, would require relying on some kind of heuristics.

**Comment by mlinksva** [comment]
Based only on a quick skim it looks like the CyconeDX bom generator implementations in this org always output a type of "library" except for npm, which looks for "framework" in a package's description https://github.com/CycloneDX/cyclonedx-node-module/blob/70eab8ee09255bc95cd96f206599257ba1c1292b/index.js#L103-L116 and maybe Java (I couldn't tell at a glance).

Similarly, it looks like modified is hardcoded to false in these implementations. That was another question I had -- it's not clear how modified would be determined automatically.

**Comment by stevespringett** [comment]
I think adding documentation for library vs framework would be a good addition. The difference is subtle and only relevant if the consumers of the BOM can process and act on the difference.

I don't think the Java version does anything with library or framework and defaults to library. Ideally, each implementation would look for key indicators of each and automatically determine the appropriate one.

The modified element was required in v1.0 and there was no way to really tell automatically. So it is now optional in 1.1 and essentially deprecated (I'll add docs) in favor of pedigree. If the library is modified, then pedigree information should be provided to include how it was modified. The official implementations will likely never be able to decipher this automatically. But the specification is open and anyone can create custom implementations that perform specific types of actions - such as getting pedigree information from an organizations version control system.

**Comment by nilp0inter** [comment]
Thank you for your responses.

I really like the clarification in fc6acef. But I it will be very hard, if not impossible, for any automated tool to properly classify dependencies between "library" and "framework". Does it worth the hassle to have this kind of differentiation in the spec?

**Comment by stevespringett** [comment]
@nilp0inter accuracy for automated selection would vary a bit and is achievable in some cases, but not all. The specification is also being used in non-automated environments - think device makers using unmanaged components, etc. There are (unfortunately) a lot of non-automated environments that still need to produce a bom, and they have the ability to make the distinction. Systems that can apply different risk weights to outdated and vulnerable components based on being a library or framework are also being worked on. Dependency-Track might go in this direction. But honestly, there are so many other enhancements in the works that are more important. Regardless, the spec provides the ability.
