### ISSUE TITLE
Question: Does CycloneDX has a spec for recording minimum required compiler version for source code?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [CycloneDX/specification#174]
for example,some.java need JDK8+
or
test.rs need rustc 1.0+

because i think it would be cool to have that information recorded especially in a foss repo,it would make readme become more clean.

**Comment by stevespringett** [comment]
This type of information is a good target for use with CycloneDX properties. We have a [formal taxonomy of properties](https://github.com/CycloneDX/cyclonedx-property-taxonomy) that can evolve independent of the CycloneDX specification. 

Within the taxonomy is the [`cdx` namespace](https://github.com/CycloneDX/cyclonedx-property-taxonomy/tree/main/cdx) where we have already defined some properties for Golang, npm, and a few others. Java and rust have not been defined yet, but absolutely should be.

I would recommend creating a few tickets over there and some pull requests that implement some of your ideas.
