### ISSUE TITLE
Can cycloneDX be generated for unmanaged package dependencies?

### ISSUE THREAD

**Issue by SanaFaiyaz** [CycloneDX/specification#18]
Hello. I am a newbie. I wanted to ask that if my software project is not using any dependency manager in its development. for eg. I am creating a java REST service and i manage all my dependencies without any tool like maven or gradle. Then is it possible to have a software bill of materials of it? to generate a cyclonedx bom so that it can be used in dependency track?

**Comment by stevespringett** [comment]
If a team is manually managing dependencies, it's certainly not a good practice, but those teams are essentially responsible for managing their BOM manually as well.

CycloneDX is simply a specification (currently just XML, but with JSON/YAML support coming soon). So anyone can write the BOM XML. There currently isn't a tool that I'm aware of that allows users to create a BOM from a UI (e.g. Electron).

There is however, a Java core library that can be used to programmatically create the BOM model which can output the resulting bom.xml.

**Comment by SanaFaiyaz** [comment]
Oh alright thanks.
Also, can you please also tell me how does the core library works in general? does it traverse through all project files and identifies libraries used? how programmatically? is there any tutorial or help about how to use it because its github documentation seems a little limited.

**Comment by stevespringett** [comment]
Files, no. The core library is just a model representation of a bom and the associated classes to generate or validate one. The various CycloneDX implementations (maven, gradle, npm, ruby gem, python, etc) perform the analysis of project files for their respective ecosystems and generate boms from them.
