### ISSUE TITLE
[Specification 1.4] differences between XML and JSON format

### ISSUE THREAD

**Issue by llaville** [CycloneDX/specification#202]
Hello,

I've noticed that [JSON specification 1.4](https://cyclonedx.org/docs/1.4/json/#specVersion)  allow to identify specification version by the `specVersion` attribute (that is cool).

But [XML specification 1.4](https://cyclonedx.org/docs/1.4/xml/) does not allow the same way to identify specification version.
The `Bom` element has only `version` and `serialNumber` attributes available. The specification version is only available through the namespace.

A concrete usage via the PHP bind library is declared at https://github.com/CycloneDX/cyclonedx-php-library/issues/283, and what I will expect is : 

Compare with actual render 

```json
{
    "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "serialNumber": "urn:uuid:7b17f9bb-3b8e-4821-9487-4d72edf29c66",
    "version": 1,

}
```

To expected result with XML format

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.4" version="1" specVersion="1.4" serialNumber="urn:uuid:7b17f9bb-3b8e-4821-9487-4d72edf29c66">

```

**Comment by jkowalleck** [comment]
in https://github.com/CycloneDX/cyclonedx-php-library/issues/283
you wrote
> It may be helpful to have the same equivalent information available

@llaville, please describe the be purpose of such an XML attribute `specVersion`.
What does this enable?

**Comment by jkowalleck** [comment]
The thing with JSON: a document might be compliant to **multiple** schemas. You cannot tell what it was scoped for. Which is intended and in the nature of the matter.
The JSON properties `bomFormat` and `specVersion` are helpers/guides (and practical boundaries) for validators and parsers. These properties help tools to determine a schema that the JSON document is checked against, so that these tools do not need to test all/multiple schemas until one passes. It might help save resources(time, computes, memory).

For XML, namespaces are **unique** and clearly identify the scope of a document. No additional helpers are needed to determine a schema, as the namespace implies the schema to use.
Be aware that an XML namespace might look like a URL, but that is just to make the namespace globally unique and owned by the owner. A namespace is just a string that determines to what schema to adhere.
While being somehow human-readable, XML is still written for machines and these are able to map an XML namespace to a certain CDX spec.

This all in mind, I see that an additional XML attribute `specVersion` might help humans, but have no benefits for machines/tools.

**Comment by llaville** [comment]
@jkowalleck I heard what you said !

Even if I'm not a big fan of XML data structure (compared to JSON, or YAML much easier to parse), let's try with a concrete example. 
Sorry for all audience, but it's for PHP language. But it won't be a problem for you Jan ;-)

Perharps I've missed something, so feel free to fix me !

I've two generated files : `sbom.xml` and `sbom.json`, and I don't know which one will be provided by the final user.

BUT my goal is to print at end of a report something like : `Generated from JSON source by CycloneDX 1.4`

When I've no problem with JSON data source, because all single informations are available : `bomFormat`, `specVersion`, I run in trouble with XML data source. 

Extracting specification version from XML namespace is not an issue, but with the bom format where can I get equivelent to JSON ?

FYI: I've removed all data (from sources) that are not really necessary for this demo purpose.

Here is a PHP test script : 
```php
<?php

function printResults(array $data, string $filename, string $bomFormat, string $specVersion): void
{
    var_dump($data);

    $source = pathinfo($filename, PATHINFO_EXTENSION);

    echo '===========================================', PHP_EOL;
    echo sprintf('Generated from %s source by %s %s', strtoupper($source), $bomFormat, $specVersion), PHP_EOL;
    echo '===========================================', PHP_EOL;
}

// Use Case 1

$filename = __DIR__ . '/sbom.xml';
$xmlString = file_get_contents($filename);

$sxe = simplexml_load_string($xmlString, null,  LIBXML_NOCDATA);
$json = json_encode($sxe);
$array = json_decode($json,true);

$namespaces = $sxe->getDocNamespaces(true);

$ns = explode('/', $namespaces['']);

$bomFormat = 'Unknown';
$specVersion = array_pop($ns);
$data = [
    "Data source (filename contents):",
    $xmlString,
    "Array Contents:",
    $array,
    "Document Namespaces",
    $namespaces,
];

printResults($data, $filename, $bomFormat, $specVersion);

// Use Case 2

$filename = __DIR__ . '/sbom.json';
$jsonString = file_get_contents($filename);

$array = json_decode($jsonString,true);

$data = [
    "Data source (filename contents):",
    $jsonString,
    "Array Contents:",
    $array,
];
$bomFormat = $array['bomFormat'];
$specVersion = $array['specVersion'];

printResults($data, $filename, $bomFormat, $specVersion);
```
That will print such following output : 

```
array(6) {
  [0]=>
  string(32) "Data source (filename contents):"
  [1]=>
  string(256) "<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.4" version="1" serialNumber="urn:uuid:aa679d23-95ea-421c-baf2-90de8f099ee0">
  <metadata>
    <timestamp><![CDATA[2023-03-29T11:47:00Z]]></timestamp>
  </metadata>
</bom>
"
  [2]=>
  string(15) "Array Contents:"
  [3]=>
  array(2) {
    ["@attributes"]=>
    array(2) {
      ["version"]=>
      string(1) "1"
      ["serialNumber"]=>
      string(45) "urn:uuid:aa679d23-95ea-421c-baf2-90de8f099ee0"
    }
    ["metadata"]=>
    array(1) {
      ["timestamp"]=>
      string(20) "2023-03-29T11:47:00Z"
    }
  }
  [4]=>
  string(19) "Document Namespaces"
  [5]=>
  array(1) {
    [""]=>
    string(35) "http://cyclonedx.org/schema/bom/1.4"
  }
}
===========================================
Generated from XML source by Unknown 1.4
===========================================
array(4) {
  [0]=>
  string(32) "Data source (filename contents):"
  [1]=>
  string(281) "{
    "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "serialNumber": "urn:uuid:bf3c1d4e-2315-4b25-91fd-4479354abe26",
    "version": 1,
    "metadata": {
        "timestamp": "2023-03-29T11:47:03Z"
    }
}
"
  [2]=>
  string(15) "Array Contents:"
  [3]=>
  array(6) {
    ["$schema"]=>
    string(47) "http://cyclonedx.org/schema/bom-1.4.schema.json"
    ["bomFormat"]=>
    string(9) "CycloneDX"
    ["specVersion"]=>
    string(3) "1.4"
    ["serialNumber"]=>
    string(45) "urn:uuid:bf3c1d4e-2315-4b25-91fd-4479354abe26"
    ["version"]=>
    int(1)
    ["metadata"]=>
    array(1) {
      ["timestamp"]=>
      string(20) "2023-03-29T11:47:03Z"
    }
  }
}
===========================================
Generated from JSON source by CycloneDX 1.4
===========================================
```

**Comment by llaville** [comment]
The previous example is perharps not so visual, and you should look at a real use case. As author of the project https://github.com/llaville/box-manifest, I'll present you my last works.

The CLI `box:compile` command allow to create a PHAR (PHP Archive) file with one or more manifest (of any format).

Here is a chunk of screenshot that was printed by the command 

![box-compile](https://user-images.githubusercontent.com/364342/228841010-fabd963f-fc0d-4525-83b1-43d5d34907d9.png)

The CLI `box:info` allow to display contents of a PHAR file.

Here is a screenshot that was printed by the command 

![display_manifests](https://user-images.githubusercontent.com/364342/228841373-e0c2970b-430f-456e-b7cf-783c3ce854d6.png)

Now, after a long introduction, have a look on code that is in charge to auto-detect file format (displayed on `box:compile` command)

https://github.com/llaville/box-manifest/blob/ea5675997b4718b10aabd23482affe4f1aa4b9c8/src/Console/Command/BoxCompile.php#L170-L180

Using Perl compatible Regular Expressions is not very easy, but it's works.

**Comment by llaville** [comment]
As workaround, I'll use what the current specification allow to me : the `metadata` -> `properties` : 
- https://cyclonedx.org/docs/1.4/json/#metadata_properties
- https://cyclonedx.org/docs/1.4/xml/#type_metadata

**Comment by jkowalleck** [comment]
> Property names of interest to the general public are encouraged to be registered in the [CycloneDX Property Taxonomy](https://github.com/CycloneDX/cyclonedx-property-taxonomy). Formal registration is OPTIONAL.
