### ISSUE TITLE
Finalize BOM Descriptor Schema Extension

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#23]
## Background
The BOM Descriptor extension is intended to provide additional metadata about the asset/software it describes. The schema is currently at 1.0-SNAPSHOT and sources and docs are here:

- https://github.com/CycloneDX/specification/blob/master/schema/ext/bom-descriptor-1.0.xsd
- https://cyclonedx.org/ext/bom-descriptor/ (v0.9 only)

**Community Feedback Requested**

**Comment by stevespringett** [comment]
An example of the BOM descriptor being used in a sample application:

```xml
<?xml version="1.0"?>
<bom serialNumber="urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79" version="1"
  xmlns="http://cyclonedx.org/schema/bom/1.1"
  xmlns:bd="http://cyclonedx.org/schema/ext/bom-descriptor/1.0">
  <components>
    <component type="library" bom-ref="pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.9">
      <group>com.fasterxml.jackson.core</group>
      <name>jackson-databind</name>
      <version>2.9.9</version>
      <purl>pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.9</purl>
    </component>
  </components>
  <bd:metadata>
    <bd:timestamp>2020-07-30T12:00:00</bd:timestamp>
    <bd:tool>
      <bd:vendor>OWASP</bd:vendor>
      <bd:name>Dependency-Track</bd:name>
      <bd:version>3.10.0</bd:version>
    </bd:tool>
    <bd:authors>
      <bd:author>
        <bd:name>Jane Wison</bd:name>
        <bd:email>jane.wilson@example.com</bd:email>
      </bd:author>
    </bd:authors>
    <bd:component type="application">
      <publisher>Acme</publisher>
      <name>Example Application</name>
      <version>1.0.0</version>
      <hashes>
        <hash alg="SHA-1">75068c26abbed3ad3980685bae21d7202d288317</hash>
      </hashes>
      <bd:licenses>
        <license>
          <name>Acme Consumer License</name>
        </license>
      </bd:licenses>
      <bd:copyright>Copyright Acme Incorporated</bd:copyright>
    </bd:component>
    <bd:manufacture>
      <bd:name>Acme</bd:name>
      <bd:url>https://www.example.com/</bd:url>
      <bd:contact>
        <bd:name>Jane Wison</bd:name>
        <bd:email>jane.wilson@example.com</bd:email>
      </bd:contact>
    </bd:manufacture>
    <bd:supplier>
      <bd:name>Acme</bd:name>
      <bd:url>https://www.example.com/</bd:url>
      <bd:contact>
        <bd:name>Jane Wison</bd:name>
        <bd:email>jane.wilson@example.com</bd:email>
      </bd:contact>
    </bd:supplier>
  </bd:metadata>
</bom>

```

**Comment by msymons** [comment]
Just to get the ball rolling...

1. In XSD, I think that the three occurrences of "for which the BOM describes"  would read better as "that the BOM describes"
2.  In Example BOM Descriptor, add a 2nd hash.  eg SHA-256, or SHA-512 to illustrate that stuff like   [sigs & sums](http://www.apache.org/dev/release-distribution#sigs-and-sums) in Apache Release Distribution Policy is covered.

**Comment by msymons** [comment]
In #7, external references were added for components.  I would like to see such references included as metadata for the BOM as a whole.   ie, URL for issue management, CI server, etc.  I envisage having the potential for (say) Jenkins to publish a BOM to Dependency-Track and for Dependency-Track to then be able to link back to the correct Jenkins project.

I also envisage that Dependency-Track might then publish the BOM (for giving to a customer, etc) *without* a bunch of these references.  After all, the URLs might not even be resolvable outside the organisation itself.

**Comment by stevespringett** [comment]
BOM-level external references are already supported in the base schema.

Refer to https://github.com/CycloneDX/specification/blob/master/schema/bom-1.1.xsd#L688. The node appears after 'components'.

```xml
<bom>
  <components>
    ...
  </components>
  <externalReferences>
    ...
  </externalReferences>
</bom>
```
