### ISSUE TITLE
Add additional component types

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#24]
In addition to the existing component types, the proposal is to add the following as new types:

- image (a vector or raster image)
- font
- container

One thing of possible confusion is the word 'container'. By container, this is meant to be equal to a Docker image or running container regardless of deployment (could be running in a standalone container or in a pod).

**Comment by taleodor** [comment]
Hi Steve, great to see the "container" type coming. One question I have is how you are thinking about linking containers to libraries and such? I.e., let's say I have a library and then I containerize it -- do you see a way to represent that it's the same library but now containerized?

**Comment by stevespringett** [comment]
CycloneDX has two different ways to represent relationships, dependency graphs, and nested components. You can also describe the final deliverable itself.

A nested component represents a system -> subsystem assembly. In other words, a component contains another component.

In the case of a container that is component of some bigger deliverable, you would basically have something like:

```xml
<component type="container">
    <name>my-custom-container</name>
    <version>1.0.0</version>
    <purl>pkg:docker/my-custom-container@sha256:cb8a924......</purl>
    <component type="library">
        <group>foo</group>
        <name>bar</name>
        <version>1.0.0</version>
        <purl>pkg:npm/foo/bar@1.0.0</purl>
    </component>
</component>
```

However, if what you're describing IS the container, then you would simply do something like this:

```xml
<component type="library">
    <group>foo</group>
    <name>bar</name>
    <version>1.0.0</version>
    <purl>pkg:npm/foo/bar@1.0.0</purl>
</component>
<bd:metadata>
    <bd:component type="container">
        <name>my-custom-container</name>
        <version>1.0.0</version>
        <purl>pkg:docker/my-custom-container@sha256:cb8a924......</purl>
    </bd:component>
</bd:metadata>
```

**Comment by stevespringett** [comment]
Note to self. Instead of describing individual types of files (image, font, etc), it may make sense to add support for mime type instead as an optional attribute on a component.

**Comment by stevespringett** [comment]
`firmware` will also be a component type in v1.2
