### ISSUE TITLE
Release notes external reference type missing from protobuf schema

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/specification#266]
This applies to all versions of the protobuf spec

**Comment by jkowalleck** [comment]
will work on this, as soon as 
https://github.com/CycloneDX/specification/pull/385
is on

**Comment by jkowalleck** [comment]
I intend to dix this in a backwards-compatible way for ALL the schemas versions we provide

**Comment by jkowalleck** [comment]
i do not understand.
none of our schemas know external references for release notes.

**Comment by andreas-hilti** [comment]
@jkowalleck In ExternalReferenceType, release-notes seems to be missing in protobuf, compared to JSON and xml:
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.proto#L214-L300
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.schema.json#L1725-L1773
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.xsd#L1313-L1534
noticed in the context of https://github.com/CycloneDX/cyclonedx-dotnet-library/pull/329

**Comment by jkowalleck** [comment]
feel free to drop a PR with a fix.

**Comment by jkowalleck** [comment]
could I ask you for a review of the proposed fix? https://github.com/CycloneDX/specification/pull/531
