### ISSUE TITLE
Protobuf: `Evidence.identity` is `repeated`, but should be `optional`

### ISSUE THREAD

**Issue by nscuro** [CycloneDX/specification#272]
The `identity` field of `Evidence` is `repeated` in the current v1.5 Protobuf schema, whereas it is a singular object in the JSON and XML variants of the schema.

https://github.com/CycloneDX/specification/blob/cc15c8550e87dfa9ee051e6795e74a3c6c641264/schema/bom-1.5.proto#L652-L658

https://github.com/CycloneDX/specification/blob/cc15c8550e87dfa9ee051e6795e74a3c6c641264/schema/bom-1.5.schema.json#L1458-L1469

https://github.com/CycloneDX/specification/blob/cc15c8550e87dfa9ee051e6795e74a3c6c641264/schema/bom-1.5.xsd#L2132-L2134

As the field is not required, it should be `optional`.

**Comment by stevespringett** [comment]
Actually, the defect is in the JSON and XML schemas. In this case, the protobuf is correct. Identity should be an array.

**Comment by stevespringett** [comment]
> I think in 1.6, we need to add some conformance tests where we serialize using proto and then attempt to deserialize and read as json and vice versa.

I think there's some tests that are performed in .NET. Perhaps @coderpatros can shed some light.

**Comment by stevespringett** [comment]
> This would be a large breaking change for cdxgen and depscan users since the identity object is used quite heavily

How would this be a breaking change? The unit tests, which incorporate both single object and arrays, are passing validation. There will be no changes required in cdxgen or depscan, although the current method (single object) has been deprecated. So implementations will be encouraged to update to supporting arrays. But no functionality is breaking.

**Comment by stevespringett** [comment]
Fix will be included in v1.6
