### ISSUE TITLE
Clarify difference between `metadata.licenses` and `metadata.component.licenses`

### ISSUE THREAD

**Issue by lfrancke** [CycloneDX/specification#273]
The JSON Schema currently has this snippet for `metadata.licenses`:

```
        "licenses": {
          "title": "BOM License(s)",
          "$ref": "#/definitions/licenseChoice"
        },
```

This gets rendered as:

![image](https://github.com/CycloneDX/specification/assets/122850/316ff6c9-7fac-4268-ac1e-2aa8617017bf)

The title is not shown making it unclear what the difference is between those two.

I suggest adding a `description`.

Similar for XML:
```
            <xs:element name="licenses" type="bom:licenseChoiceType" minOccurs="0" maxOccurs="1"/>
```

**Comment by jkowalleck** [comment]
`metadata.licenses` is the license of the CycloneDX document.
the other one is the license of the component descibed by the document. 


I will update the documentation on the schema files.

**Comment by jkowalleck** [comment]
could I ask you for a review of https://github.com/CycloneDX/specification/pull/370 ?

**Comment by stevespringett** [comment]
@jkowalleck is this still outstanding?

**Comment by stevespringett** [comment]
Or can it be closed?

**Comment by jkowalleck** [comment]
i intended to close it via https://github.com/CycloneDX/cyclonedx.org/issues/281
I'd say it can be closed, but i'd appreciate if @lfrancke could review the already merged https://github.com/CycloneDX/specification/pull/378
and tell if the change was suffitient, so that this issue might be closed

**Comment by lfrancke** [comment]
I only have one comment on #378 
But yes: I'm happy to close this either way. It's much clearer now, thank you!

**Comment by jkowalleck** [comment]
open question from @lfrancke : https://github.com/CycloneDX/specification/pull/378/files#r1501878816

**Comment by jkowalleck** [comment]
all done
