### ISSUE TITLE
Add 'category' field to machine-learning-model component

### ISSUE THREAD

**Issue by bardenstein** [CycloneDX/specification#281]
Request: add a `category` field to the mlm component. 

- Required: true
- Type: String
- Examples: "text-generation," "image-processing," "image-generation," etc. 
- Justification: model types are part of the standard model card for HuggingFace, the largest repository of open-source models. The type field also helps the end user understand what category of model this is and its primary functionality.

**Comment by bardenstein** [comment]
@stevespringett from the people I discussed, a string or ENUM seems to represent a vast majority of the data in the wild I see in model cards. To your point, I'd suggest we start with the string until we collect enough data to formalize some ENUM values.

**Comment by jkowalleck** [comment]
@bardenstein the CycloneDX CoreWorkingGroup proposes to start with a CycloneDX propery.
You could define and register theres here: https://cyclonedx.github.io/cyclonedx-property-taxonomy/

Examples of others colaborating on property taxnomy: 
- the current rust standardisation - https://github.com/CycloneDX/cyclonedx-property-taxonomy/issues/75 

If the maturity of this property reaches a certain level, we could standardice on it.

**Comment by jkowalleck** [comment]
@stevespringett and @mrutkows proposed to call it "tags" on the `component` level, instead of "category"
this way we could have tags like
- `xml-parser` for a component of type `library`
- `image-generator` for a component of machine-learnign type
