### ISSUE TITLE
Add more documentation around `components[].scope`

### ISSUE THREAD

**Issue by noqcks** [CycloneDX/specification#293]
The CycloneDX standard includes a `scope` attribute for each component:

![image](https://github.com/CycloneDX/specification/assets/4740147/c4b2c008-4671-4a4e-bdd8-cd51838d06c3)

I am confused about when one should use `required`, `optional` or `excluded` when generating an entry for a component. Are there any examples? Could the description be altered to make this more clear?

**Comment by stevespringett** [comment]
`scope` is a way to include a component but not assert that that component is delivered or included in the inventory. For example, you may want to include `Windows XP Embedded` as a component, mark the scope as excluded, as a way to indicate that the entire stack will include the OS, but that the supplier does not provide it with the software. There is ongoing discussions within CISA on how to specify runtime requirements. Expect this capability to expand in the future.

**Comment by stevespringett** [comment]
With that said, we will expand the documentation for v1.6. Thanks for the suggestion.

**Comment by jkowalleck** [comment]
seams to be fixed via https://github.com/CycloneDX/specification/commit/d92e58efe09a384ce1b68ff1b7808903feb26d38
