### ISSUE TITLE
Inappropriate test data in invalid-license-id-count

### ISSUE THREAD

**Issue by tokcum** [CycloneDX/specification#303]
Hi,

working on [cyclonedx-rust-cargo](https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/399), I'm experiencing that `invalid-license-id-count` test data unexpectedly fails validation.

The code of cyclonedx-rust-cargo does not yet check for doubly defined `id` in `license`. However, the corresponding validation test fails.

Let me explain by referring to an example in _invalid-license-id-count-1.4.xml_, see below. From the test data's file name and comment provided in the file, I understand that defining `id` twice is no longer valid. In fact, the test concludes that this BOM is invalid. However, this is not because of the doubly defined `id` but because of the invalid license identifier: Apache-2 is not a valid SPDX identifier.

This is expected to fail and it fails but due to the wrong reason:
```
<licenses>
                <license>
                    <id>Apache-2</id>
                    <!-- This was a defect in schema 1.0 and is no longer permitted -->
                    <id>Apache-2</id>
                </license>
</licenses>
```

After changing the id to a valid SPDX identifier, the test unexpectedly passes validation. Of course, to make this fail, I've to update cyclonedx-rust-cargo. However, the test data is inappropriate to conduct this test and needs to be refined.

```
<licenses>
                <license>
                    <id>Apache-2.0</id>
                    <!-- This was a defect in schema 1.0 and is no longer permitted -->
                    <id>Apache-2.0</id>
                </license>
</licenses>
```

I'll file a PR to fix this. However, I want to check for other occurrences of this issue within test data.

**Comment by tokcum** [comment]
The following files are affected by this issue:

invalid-license-id-count-1.[1-5].xml

Fun fact: my IDE even points me in the right direction. When I fix the SPDX Identifier, it correctly states that a double id attribute is not allowed.

![Screenshot_2023-09-12_09-42-34](https://github.com/CycloneDX/specification/assets/47994370/f3e92161-cf02-4cc9-be71-374501348a97)

**Comment by jkowalleck** [comment]
thanks for bringing this to our attention.

your report solution sound reasonable. :+1: 
please pullrequest your desired solution.

**Comment by jkowalleck** [comment]
maybe use `MIT` as the SPRDX license ID in the tests.
It is shorter and easier to remember, and it is less likely to do mistakes
