### ISSUE TITLE
Question about cdx standard - Affects

### ISSUE THREAD

**Issue by javixeneize** [CycloneDX/specification#308]
Hi

I have a quick question about the "affects" field in vulnerabilities.

The standard says:
```json5
{
"affects": {
          "type": "array",
          "uniqueItems": true,
          "additionalItems": false,
          "items": {
            "required": [
              "ref"
            ],
            "additionalProperties": false,
            "properties": {
              "ref": {
                "$ref": "#/definitions/refType",
                "title": "Reference",
                **"description": "References a component or service by the objects bom-ref"**
              },
}
```
However, i have seen some sboms where the object referenced in affects is the purl instead of bom-ref

I am aware that the recommendation is to use the purl as bom-ref, but in the examples i have seen, this is not the case, as for example:
```json5
{
  "purl" : "pkg:maven/org.springframework.boot/spring-boot-starter-logging@2.3.12.RELEASE",
  "bom-ref" : "urn:cdx:org.springframework.boot:spring-boot-starter-logging:2.3.12.RELEASE"
}
```
Can you advise if my understanding is correct, and in affects, the object referenced should be the `bom-ref`? 

Thanks

**Comment by jkowalleck** [comment]
> However, i have seen some sboms where the object referenced in affects is the purl instead of bom-ref

the `affects[].ref` is either a reference of an in-document `bom-ref` or a [BOM-Link](https://cyclonedx.org/capabilities/bomlink/) another document's `bom-ref`.

here are valid examples: https://github.com/CycloneDX/bom-examples/blob/master/VEX

**Comment by javixeneize** [comment]
100%, so, sboms that refer to purl instead of bom-ref, are non compliant with cdx standard, correct?

**Comment by jkowalleck** [comment]
> 100%, so, sboms that refer to purl instead of bom-ref, are non compliant with cdx standard, correct?

correct.
It MUST be references to `bom-ref`s, either in-document or BOM-Link.

**Comment by javixeneize** [comment]
thanks!
