### ISSUE TITLE
Add bom level component properties

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/specification#32]
I think it would be good to add some component properties at the bom level.

For example, including the purl of the package that the sbom describes.

**Comment by stevespringett** [comment]
I think this use case is handled by the [BOM Descriptor extension](https://cyclonedx.org/ext/bom-descriptor/) for CycloneDX v1.1 and the [built-in metadata node](https://cyclonedx.org/use-cases/#packaging-and-distribution) in CycloneDX v1.2.

Ideally, I'd like to see every CycloneDX implementation output the metadata node and describe the root component as well as the tool used to create the BOM.

**Comment by coderpatros** [comment]
:facepalm: don't know how I missed that. Must have been looking at the 1.1 spec instead of 1.2.
