### ISSUE TITLE
[Dependency Graph] How to identify direct / indirect dependencies

### ISSUE THREAD

**Issue by mscudlik** [CycloneDX/specification#33]
With the current dependency graph specification, it seems to be not possible to exactly distinguish between direct and indirect dependencies. 

Example:
Given the following dependency graph (taken from https://cyclonedx.org/ext/dependency-graph/):

```xml
    <dg:dependencies>
        <dg:dependency ref="pkg:maven/org.example.acme/web-framework@1.0.0">
            <dg:dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
        </dg:dependency>
        <dg:dependency ref="pkg:maven/org.example.acme/persistence@3.1.0">
            <dg:dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
        </dg:dependency>
        <dg:dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    </dg:dependencies>
```

Analyzing/interpreting the dependency graph, we can clearly identify the following:
Direct dependencies
- `pkg:maven/org.example.acme/web-framework@1.0.0`
- `pkg:maven/org.example.acme/persistence@3.1.0`

Indirect dependencies
- `pkg:maven/org.example.acme/common-util@3.0.0`

But we can actually **not** conclude is if `pkg:maven/org.example.acme/common-util@3.0.0` is a direct dependecy as well

Is this a known issue or done on purpose? And if so, why? 
If not, is it possible to include this into the specification to resolve this issue?

Thanks and best regards,
Matthias

**Comment by stevespringett** [comment]
Sure it can.

Assuming the component defined in the bom metadata section has a bom-ref of `acme-app`, then the graph would like like:

```xml
<dependencies>
    <dependency ref="acme-app">
        <dependency ref="pkg:maven/org.example.acme/web-framework@1.0.0">
        <dependency ref="pkg:maven/org.example.acme/persistence@3.1.0">
    <dependency>
    <dependency ref="pkg:maven/org.example.acme/web-framework@1.0.0">
        <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    <dependency>
    <dependency ref="pkg:maven/org.example.acme/persistence@3.1.0">
        <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    </dependency>
    <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
</dependencies>
```

This would indicate that common-util is NOT a direct dependency of acme-app. If you wanted to indicate it IS a direct dependency, in addition to being a transitive dependency, then it would look like this:

```xml
<dependencies>
    <dependency ref="acme-app">
        <dependency ref="pkg:maven/org.example.acme/web-framework@1.0.0">
        <dependency ref="pkg:maven/org.example.acme/persistence@3.1.0">
        <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    <dependency>
    <dependency ref="pkg:maven/org.example.acme/web-framework@1.0.0">
        <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    <dependency>
    <dependency ref="pkg:maven/org.example.acme/persistence@3.1.0">
        <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
    </dependency>
    <dependency ref="pkg:maven/org.example.acme/common-util@3.0.0"/>
</dependencies>
```

**Comment by stevespringett** [comment]
Note to self, improve the use cases documentation to account for this scenario.

**Comment by stevespringett** [comment]
Examples at https://cyclonedx.org/use-cases/#dependency-graph have been updated.

If you're using CycloneDX v1.1, you'll need to use both the dependency-graph extension and the bom-descriptor extension to accomplish this. With CycloneDX v1.2, no extensions required.
