### ISSUE TITLE
Schema "bom-1.5.xsd" is different from "bom-1.5.schema.json"

### ISSUE THREAD

**Issue by SpessartZiegler** [CycloneDX/specification#330]
If I validate a JSON file with no id or name for a license I got an error.
The schema is clear for me (see "Schema JSON.jpg" oneOf required.)
![Schema JSON](https://github.com/CycloneDX/specification/assets/2765863/d8b5ea67-9b2d-4ec7-bc33-e8bf16351cf5)

If I validate a XML file with no id or name for a license I got the message that the file is okay.
It's clear for me (see "XSD,jpg" choice minOccurs="0")
![XSD](https://github.com/CycloneDX/specification/assets/2765863/c7b9364e-949c-4bd4-953f-35c6d35cca31)

If I change the minOccurs for id and name to "1" then the validation generates an error that the id or name is missing for a license.

It is the same for other "Choice"s in the XSD. In my point of view you will not get the same validation for JSON and XML files. Especially if you convert a valid XML file to JSON you will get an invalid file because some required entries are missing.

[XSD.zip](https://github.com/CycloneDX/specification/files/13218793/XSD.zip)

**Comment by jkowalleck** [comment]
duplicates #288

**Comment by jkowalleck** [comment]
the JSON schema is the correct one for this particular detail.
the XML schema will be adjusted in v1.6 -- probably via https://github.com/CycloneDX/specification/pull/292
