### ISSUE TITLE
SBOM Specification does not include information for which software the SBOM has been created 

### ISSUE THREAD

**Issue by mscudlik** [CycloneDX/specification#34]
The SBOM specification currently defines a format for a Software Bill of Material and lists all components/dependencies of the software. What seems to be not included, is information about "the software itself", meaning information for which software the SBOM has been created. 

Is there a specific reason for this or would it be possible extend the specification, so that there is a "section" which explicitly defines "the software itself"?

Thanks and best regards,
Matthias

**Comment by stevespringett** [comment]
If you're using CycloneDX v1.1, there's the BOM Descriptor extension that provides this capability.
https://cyclonedx.org/ext/bom-descriptor/

That extension, with some enhancements, is included in the base CycloneDX v1.2 specification. 
https://cyclonedx.org/use-cases/#packaging-and-distribution
