### ISSUE TITLE
New field: `component.modelcard.modelType`

### ISSUE THREAD

**Issue by bardenstein** [CycloneDX/specification#340]
**Proposal**
Add a "model type" field to the model card block that allows uses to input common 'types' of distinguishing models, such as "text-generation", "image-to-text", etc. These are standard on Hugging Face and other sources for open-source models.

**Details**
FieldName: Components.modelCard.modelType
FieldType: string
Required: no
Examples: "text-generation", "image-to-text," "text-to-image"

**Example snippet**

```json
"modelCard" : [
       "modelType": "text-to-image"
  ]
```

**Comment by bardenstein** [comment]
@stevespringett consider the options listed on the left side of the https://huggingface.co/models page:

<img width="371" alt="Screen Shot 2023-12-07 at 9 57 43 PM" src="https://github.com/CycloneDX/specification/assets/862262/c2730715-79a3-486b-94bf-362e738c69f6">

**Comment by stevespringett** [comment]
@chrish42 Do you have any thoughts on this proposal?

**Comment by stevespringett** [comment]
This was implemented with tags. See #383 which will be included in v1.6.
