### ISSUE TITLE
Should `manufacture` be a property of `component`, rather than `metadata`?

### ISSUE THREAD

**Issue by nscuro** [CycloneDX/specification#346]
The majority of fields under `metadata` refer to the BOM itself. 

However, `metadata.manufacture` technically refers to `metadata.component`:

https://github.com/CycloneDX/specification/blob/299209abd9531d808e0cc4235e77a7c4b1b53d96/schema/bom-1.5.schema.json#L263-L267

This can cause confusion because, as mentioned, everything else refers to the BOM, not `metadata.component`.

Should `manufacture` be a property of `component` instead, to make the association more clear?

**Comment by stevespringett** [comment]
IMO, we should likely add manufacturer to component and update the description of manufacture in the metadata section to reflect the BOM. Thoughts @jkowalleck @coderpatros

**Comment by coderpatros** [comment]
I agree with that

**Comment by jkowalleck** [comment]
> add manufacturer to component

we already have `component.group` for that, right? 
> The grouping name or identifier. This will often be a shortened, single name of the company or project that produced the component, or the source package or domain name. Whitespace and special characters should be avoided. Examples include: apache, org.apache.commons, and apache.org.

----

> update the description of manufacture in the metadata section to reflect the BOM

Though this would not change the schema, it still would be a change of the meaning of an element. Which would be a breaking change.

**Comment by stevespringett** [comment]
Is this something we want to address for v1.6?

**Comment by jkowalleck** [comment]
> IMO, we should likely add manufacturer to component and update the description of manufacture in the metadata section to reflect the BOM. Thoughts @jkowalleck @coderpatros

sounds good

will open a pullrequest adding the component manufacturer to components.
