### ISSUE TITLE
typo in CDX 1.6 counterClaim title

### ISSUE THREAD

**Issue by idunbarh** [CycloneDX/specification#373]
Theres a minor typo in the title of the counterClaim field in the attestation capabilities.
- https://github.com/CycloneDX/specification/blob/1.6-dev/schema/bom-1.6.schema.json#L181

I'll submit a PR.

**Comment by jkowalleck** [comment]
> I'll submit a PR. 

<3 go ahead

**Comment by stevespringett** [comment]
Thanks for identifying and correcting the issue.
