### ISSUE TITLE
RFC CycloneDX IANA media type registration

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/specification#45]
Suggest we register official media types with IANA.

Use cases include API end points that can return SBOMs.

This could either be just to communicate to consumers the format provided. Or allow specifying which SBOM format is desired during the request.

Suggested media types are `application/cyclonedx+xml` and `application/cyclonedx+json`.

Although I need to re-read the relevant RFCs for any gotchas/requirements.

**Comment by stevespringett** [comment]
Related to OPSAWG thread that references registering mime types for CycloneDX (and other formats) for use with `.well-known`. 

https://www.mail-archive.com/opsawg@ietf.org/msg04737.html

**Comment by coderpatros** [comment]
I think the media types will need to be something like `application/vnd.cyclonedx+xml` and `application/vnd.cyclonedx+json`.

To avoid the `vnd` prefix the standard needs to be published as an IETF RFC. And IMHO that would just cause too much friction.

**Comment by coderpatros** [comment]
IANA registrations have been submitted for `application/vnd.cyclonedx+xml` and `application/vnd.cyclonedx+json`

**Comment by coderpatros** [comment]
IANA media types have been assigned.

https://www.iana.org/assignments/media-types/application/vnd.cyclonedx+xml
https://www.iana.org/assignments/media-types/application/vnd.cyclonedx+json

**Comment by stevespringett** [comment]
Absolutely fantastic Patrick.
