### ISSUE TITLE
[Defect]: Protobuf serialization does not allow to specify bom-ref for license expressions

### ISSUE THREAD

**Issue by andreas-hilti** [CycloneDX/specification#515]
## Describe the defect

The protobuf serialization does not allow to specify a bom-ref for license expressions, in contrast to the xml and JSON serialization:
https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.proto#L368-L376
https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.schema.json#L1498-L1502
https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.xsd#L2279-L2286

## Additional context

n/a

**Comment by jkowalleck** [comment]
@stevespringett i would pull a fix for this in the upcoming 1.6.1 - if this was okay?

**Comment by stevespringett** [comment]
Perfect @jkowalleck

**Comment by jkowalleck** [comment]
Thank you very much for the report, @andreas-hilti 

could I ask you to review the proposed fix? <https://github.com/CycloneDX/specification/pull/529>
