### ISSUE TITLE
[bug]: Inconsistent number of occurrences for `definitions.standards.requirements.descriptions`

### ISSUE THREAD

**Issue by hakandilek** [CycloneDX/specification#528]
The number of occurrences in the JSON, XML and Protobuf Schemas are different for the 
 `definitions.standards.requirements.descriptions` field.

In JSON schema we have `descriptions` array:
https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.schema.json#L4950-L4955
where the following would be possible:
```json
  "descriptions": [
    "Requirement is described here",
    "and here"
  ],

```

In the XML schema we have `0..1` `descriptions/description` entries:
https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.xsd#L8022-L8033
where this would *not* be possible:
```xml
  <descriptions>
    <description>Requirement is described here</description>
    <description>and here</description>
  </descriptions>
```

In the Protobuf schema `Definition.Standard.Requirement.descriptions` is a text field:

https://github.com/CycloneDX/specification/blob/bfb6f8baf77bbf98a4c0a54392508ba3ccf2e22e/schema/bom-1.6.proto#L1888-L1889

Already discussed this with @jkowalleck during python-lib improvements and decided that we should address it here.

**Comment by jkowalleck** [comment]
@stevespringett is this something we would put in an interim bugfix release, or do we wait until 1.7 ?

**Comment by stevespringett** [comment]
Looks like the JSON and Protobuf are good, but `description` should be `unbounded` in the XML. @jkowalleck lets go ahead and do a point release for the XML only if that makes sense to you. If so, would you mind doing it. I'm traveling for the next two weeks.

**Comment by hakandilek** [comment]
> Looks like the JSON and Protobuf are good, but `description` should be `unbounded` in the XML. [@jkowalleck](https://github.com/jkowalleck) lets go ahead and do a point release for the XML only if that makes sense to you. If so, would you mind doing it. I'm traveling for the next two weeks.

**Comment by hakandilek** [comment]
I might be able to provide a patch for this next week.

**Comment by jkowalleck** [comment]
i will merge @hakandilek's upcoming patch and do the dot release for XML.

**Comment by jkowalleck** [comment]
@hakandilek ,

When preparing a fix, please also extend the related test files: 
- <https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.6/valid-standard-1.6.json>
- <https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.6/valid-standard-1.6.xml>
- <https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.6/valid-standard-1.6.textproto>

it appears that there is no case with multiple descriptions, yet.

Thank you very much in advance.

**Comment by hakandilek** [comment]
> When preparing a fix, please also extend the related test files:

Sure, fix is in place. Test files to follow.
