### ISSUE TITLE
Spelling mistake in 1.6 xsd

### ISSUE THREAD

**Issue by weaversa** [CycloneDX/specification#547]
Something small I noticed -- https://github.com/CycloneDX/specification/blob/268138039498a4f390ddc5d7e7e78857a951986f/schema/bom-1.6.xsd#L2675

'opyright' is missing the first 'c'.

**Comment by jkowalleck** [comment]
thanks for reporting this, @weaversa 

could you drop us a pull request with the needed changes?

**Comment by weaversa** [comment]
Please see #550 for some minor updates.
