### ISSUE TITLE
Add JSON Schema to Schemastore

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#60]
Add CycloneDX v1.2 and v1.3 to https://www.schemastore.org/ once v1.3 has been published.

**Comment by coderpatros** [comment]
I was going to knock this off @stevespringett 

Noticed you started preparing this in a fork. Any reason we aren't opting to just reference the self hosted schemas on cyclonedx.org?

**Comment by stevespringett** [comment]
use the self-hosted schemas if you want. I was doing it at a time when lots of other activity was happening in that repo - so I was constantly running into merge conflicts. It was a serious PITA with the whole manual approval for PRs that Github introduced when there's a lot of activity in modifying a single file.

**Comment by jkowalleck** [comment]
The JSON schemastore is for “assigning” well-known files to a JSON schema.
Even though we have [recognized-file-patterns for CDX](https://cyclonedx.org/specification/overview/#recognized-file-patterns) , I think it is a stupid idea to go with the schema store.

We do actually host our schema under the URL that is used as the schema-ID.
If BOM-generators could simply add the appropriate `$schema` to the document, all was good.
see also: 
- https://github.com/CycloneDX/specification/issues/254
- https://github.com/CycloneDX/cyclonedx.org/issues/70

**Comment by jkowalleck** [comment]
@CycloneDX/core-team 
as discussed in today's CoreWorkingGroup meeting, I will close task as "not planned" 
for the greed reasons of https://github.com/CycloneDX/specification/issues/60#issuecomment-1630484193
