### ISSUE TITLE
Make unit tests dynamic

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#62]
Currently, all unit tests are statically specified in test classes, one for XML, one for JSON.

This ticket describes a refactor to support dynamic test cases based on the existing filename conventions used by the test cases.

Example pattern is:
[in]valid-xxxxxxx-1.0.xml
[in]valid-xxxxxxx-1.0.json

All test files that conform to the pattern will be automatically tested without further code changes.

**Comment by stevespringett** [comment]
Implemented and verified.

**Comment by coderpatros** [comment]
Very nice
