### ISSUE TITLE
Add ExternalReferenceType SW360

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/specification#82]
We use SW360 (https://github.com/eclipse/sw360) as a platform for sharing the clearing information of each 3rdParty component within our organisation. It would be good to add the SW360 ID or URL for each component as external reference so that I can easily find my entry in SW360.
So I want to add SW360 to "externalReferenceType": 
<xs:simpleType name="externalReferenceType">
   <xs:restriction base="xs:string">
      <xs:enumeration value="vcs"/>
      <xs:enumeration value="issue-tracker"/>
      <xs:enumeration value="website"/>
      <xs:enumeration value="advisories"/>
      <xs:enumeration value="bom"/>
      <xs:enumeration value="mailing-list"/>
      <xs:enumeration value="social"/>
      <xs:enumeration value="chat"/>
      <xs:enumeration value="documentation"/>
      <xs:enumeration value="support"/>
      <xs:enumeration value="distribution"/>
      <xs:enumeration value="license"/>
      <xs:enumeration value="build-meta"/>
      <xs:enumeration value="build-system"/>
      **<xs:enumeration value="sw360"/>**
      <xs:enumeration value="other"/>
   </xs:restriction>
</xs:simpleType>

**Comment by coderpatros** [comment]
My initial thought is that such specific external reference types are not a good idea.

And this approach in the future is limited to evolving needs like this. It would require waiting for a new spec version to be able to add support. I'd much prefer a more flexible solution for this use case.

One thing I've wondered is if we should add the available media types to the external reference. SW360 doesn't have a media type registration to my knowledge. Although it would probably be pretty easy to reach out to the SW360 folks and get an agreed on vendor tree media type for this type of thing.

**Comment by patspaeth** [comment]
Yes understood. 
I just need a place where I can store either the unique ID or the link to the component in SW360 component catalogue. The purpose is to map components in the platform to my SBOM - esp. when there is already a component added manually but with a different name. (e.g. dotnet vs. .net)
Maybe we can have a more generic name like "sw component catalogue" - because SW360 is not the only catalogue like your dependecyTrack platform.
Meanwhile I think I will use "other" to store the reference - or is there a better place I miss?

**Comment by coderpatros** [comment]
Yeah, I think "other" is the probably the best spot right now.
