### ISSUE TITLE
Harden JSON Schema

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#89]
The JSON schema, by default, is relaxed and allows undefined properties to appear anywhere in the document. An optional strict schema is provided that disallows this behavior.

This proposal would:
* eliminate the relaxed schema
* JSON schema would not allow undefined properties to appear (strict)

Impacts:
* JSON serialization format would not provide a playground for extensions. This may not be overly impactful as support for Properties were introduced in v1.3 which eliminates most of the need for extensions. Additionally, JSON extensions were problematic anyway as JSON Schema is not extensible in the same way XML is.
* Enveloped signing will need to be specified as part of the JSON spec (not the XML spec???). This is due to JSON not supporting namespaces. Therefore we will need to define the parts of the SBOM that are the most likely to be signed.  This will likely be scoped to:
  * bom
  * component
  * service

**Comment by coderpatros** [comment]
I think we should add it to the xml spec too. Be good to have a hardened xml spec too.

**Comment by coderpatros** [comment]
I think we should add it to the xml spec too. Be good to have a hardened xml spec too.

**Comment by stevespringett** [comment]
I've reached out to NSA to see if they've evaluated CycloneDX. I know it was on their todo. Not sure if they've gotten around to it yet.

**Comment by stevespringett** [comment]
I heard back from Anders Rundgren, the author of JSF from webpki.org and a JSON schema does not exist for JSF at the moment. However, his recommendations would be to create a subset of JSF for our use cases. As long as we require [RFC 8785](https://datatracker.ietf.org/doc/html/rfc8785), which he recently got through, we should be good.
