### ISSUE TITLE
Change component version to optional

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#90]
For 'file' components, version information may not be specified in the file or it may be difficult to determine without deeper analysis.

This proposal is to make version optional in the spec. Currently it is required.

Due to it being required, some workarounds have been practiced including using semver along with truncated SHA1 hash. For example: `0.0.0-ab5c2cdf`.

**Comment by coderpatros** [comment]
Big +1 from me

**Comment by stevespringett** [comment]
With the proposed changes in #38, specifically the example here : df947e91edd6c8b37f0f6a5672834424c0240c33

It will be possible to use CycloneDX as an advisory format when the component version is omitted.
